"""Shared enum values for persistence and services."""

from enum import StrEnum


class WatchedDirectoryStatus(StrEnum):
    """Lifecycle states for a watched directory."""

    NORMAL = "NORMAL"
    PENDING = "PENDING"
    BACKING_UP = "BACKING_UP"
    ERROR = "ERROR"
    IGNORED = "IGNORED"


class AuditEvent(StrEnum):
    """Suggested audit action/result values."""

    BACKUP_OK = "BACKUP_OK"
    BACKUP_SKIPPED = "BACKUP_SKIPPED"
    BACKUP_OMITTED = "BACKUP_OMITTED"
    MANUAL_BACKUP_STARTED = "MANUAL_BACKUP_STARTED"
    MANUAL_BACKUP_GROUP_STARTED = "MANUAL_BACKUP_GROUP_STARTED"
    MANUAL_BACKUP_GROUP_FINISHED = "MANUAL_BACKUP_GROUP_FINISHED"
    MANUAL_BACKUP_GROUP_ERROR = "MANUAL_BACKUP_GROUP_ERROR"
    MANUAL_BACKUP_FINISHED = "MANUAL_BACKUP_FINISHED"
    RESTORE_STARTED = "RESTORE_STARTED"
    RESTORE_OK = "RESTORE_OK"
    RESTORE_ERROR = "RESTORE_ERROR"
    RESTORE_ABORTED = "RESTORE_ABORTED"
    RETENTION_BY_COUNT = "RETENTION_BY_COUNT"
    RETENTION_BY_AGE = "RETENTION_BY_AGE"
    RETENTION_FILE_MISSING = "RETENTION_FILE_MISSING"
    RETENTION_ERROR = "RETENTION_ERROR"
    TASK_SCHEDULER_ENABLE_BOOT = "TASK_SCHEDULER_ENABLE_BOOT"
    TASK_SCHEDULER_RUN_NOW = "TASK_SCHEDULER_RUN_NOW"
    TASK_SCHEDULER_DISABLE_TEMPORARY = "TASK_SCHEDULER_DISABLE_TEMPORARY"
    TASK_SCHEDULER_DISABLE_UNTIL_BOOT = "TASK_SCHEDULER_DISABLE_UNTIL_BOOT"
    TASK_SCHEDULER_DISABLE = "TASK_SCHEDULER_DISABLE"
    TASK_SCHEDULER_RESUME = "TASK_SCHEDULER_RESUME"
    TASK_SCHEDULER_OK = "TASK_SCHEDULER_OK"
    TASK_SCHEDULER_ERROR = "TASK_SCHEDULER_ERROR"
    WARNING = "WARNING"
    ERROR_ZIP = "ERROR_ZIP"
    ERROR_READ = "ERROR_READ"
    NO_EFFECTIVE_CHANGES = "NO_EFFECTIVE_CHANGES"
